### ISSUE TITLE
lib.info should be lib.album or lib.album_info

### ISSUE THREAD

**Issue by siznax** [siznax/moo#15]
"info" is simply too generic. This information should line up with ``album`` in our code reference https://github.com/siznax/moo/wiki/%F0%9F%8E%B7-Reference

**Comment by khafrewatkins** [comment]
Hi, can you give a little more detail on what you want done?  The descriptions do look generic as you described it.

**Comment by siznax** [comment]
Thanks for posting, @khafrewatkins.  This is "simply" a name change.

We need to change ``lib.info()`` to ``lib.album()`` in https://github.com/siznax/moo/blob/main/Moo/play/lib.py

``lib.album()`` already exists, but it is not being used. So, here are the steps:

1. Delete the ``lib.album()`` function
2. Rename ``lib.info()`` to ``lib.album()``
3. Replace ``lib.info()`` with ``lib.album()`` in the rest of the code
4. Replace the variable name ``info`` with ``album_info`` where applicable

Now that I've listed the steps, I realize this may not be a good first issue?

**Comment by khafrewatkins** [comment]
Hi, this is perfect!  I can handle this.  Thank you so much!

Khafre
